blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/kpblc/update-singbox/blob/main/README.md
    about: Please check the documentation before opening an issue
  - name: 💬 Discussions
    url: https://github.com/kpblc/update-singbox/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/kpblc/update-singbox/security/advisories/new
    about: Report security vulnerabilities privately
