"""Configuration models for various proxy protocols.

This module contains Pydantic models for different proxy configuration formats:
- sing-box: Complete sing-box configuration models
- xray: Xray/V2Ray configuration models (planned)
- clash: Clash/Mihomo configuration models (planned)
"""

# Sing-box models
from .singbox import (  # Main config; Enums; Common; DNS; Auth; NTP; Inbounds; Outbounds; Routing; Experimental; Observatory
    AnyTlsOutbound,
    AuthenticationConfig,
    BlockOutbound,
    CacheFileConfig,
    ClashApiConfig,
    DirectInbound,
    DirectOutbound,
    DnsConfig,
    DnsOutbound,
    DnsRule,
    DnsServer,
    DomainStrategy,
    ExperimentalConfig,
    HttpInbound,
    HttpOutbound,
    Hysteria2Inbound,
    Hysteria2Outbound,
    HysteriaOutbound,
    Inbound,
    InboundBase,
    LogLevel,
    MixedInbound,
    MultiplexConfig,
    Network,
    NtpConfig,
    ObservatoryConfig,
    Outbound,
    OutboundBase,
    RouteConfig,
    RouteRule,
    SelectorOutbound,
    ShadowsocksInbound,
    ShadowsocksOutbound,
    ShadowTlsInbound,
    ShadowTlsOutbound,
    SingBoxConfig,
    SocksInbound,
    SocksOutbound,
    SshOutbound,
    TlsConfig,
    TorOutbound,
    TransportConfig,
    TrojanInbound,
    TrojanOutbound,
    TuicInbound,
    TuicOutbound,
    UrlTestOutbound,
    User,
    V2RayApiConfig,
    VlessInbound,
    VlessOutbound,
    VmessInbound,
    VmessOutbound,
    WireGuardInbound,
    WireGuardOutbound,
)

# Утилиты (новые или совместимые с новой схемой)
# (Если нужны create_example_config, validate_config и т.д. — импортировать из singbox/utils.py или аналогичного файла)

__all__ = [
    # Sing-box models
    "SingBoxConfig",
    "LogLevel",
    "Network",
    "DomainStrategy",
    "TlsConfig",
    "MultiplexConfig",
    "TransportConfig",
    "DnsConfig",
    "DnsServer",
    "DnsRule",
    "AuthenticationConfig",
    "User",
    "NtpConfig",
    "InboundBase",
    "MixedInbound",
    "SocksInbound",
    "HttpInbound",
    "ShadowsocksInbound",
    "VmessInbound",
    "VlessInbound",
    "TrojanInbound",
    "Hysteria2Inbound",
    "WireGuardInbound",
    "TuicInbound",
    "ShadowTlsInbound",
    "DirectInbound",
    "Inbound",
    "OutboundBase",
    "ShadowsocksOutbound",
    "VmessOutbound",
    "VlessOutbound",
    "TrojanOutbound",
    "Hysteria2Outbound",
    "WireGuardOutbound",
    "HttpOutbound",
    "SocksOutbound",
    "TuicOutbound",
    "ShadowTlsOutbound",
    "DnsOutbound",
    "DirectOutbound",
    "BlockOutbound",
    "SelectorOutbound",
    "UrlTestOutbound",
    "HysteriaOutbound",
    "AnyTlsOutbound",
    "SshOutbound",
    "TorOutbound",
    "Outbound",
    "RouteConfig",
    "RouteRule",
    "ExperimentalConfig",
    "ClashApiConfig",
    "V2RayApiConfig",
    "CacheFileConfig",
    "ObservatoryConfig",
]
