"""Models package for SBoxMgr.

This package contains all Pydantic models used throughout the application.
"""

# This file indicates that the package supports type checking
# See PEP 561 for more details

# Sing-box models
from .singbox import (  # Main config; Enums; Common; DNS; Auth; NTP; Inbounds; Outbounds; Routing; Experimental; Observatory
    AnyTlsOutbound,
    AuthenticationConfig,
    BlockOutbound,
    CacheFileConfig,
    ClashApiConfig,
    DirectInbound,
    DirectOutbound,
    DnsConfig,
    DnsOutbound,
    DnsRule,
    DnsServer,
    DomainStrategy,
    ExperimentalConfig,
    HttpInbound,
    HttpOutbound,
    Hysteria2Inbound,
    Hysteria2Outbound,
    HysteriaOutbound,
    Inbound,
    InboundBase,
    LogLevel,
    MixedInbound,
    MultiplexConfig,
    Network,
    NtpConfig,
    ObservatoryConfig,
    Outbound,
    OutboundBase,
    RouteConfig,
    RouteRule,
    SelectorOutbound,
    ShadowsocksInbound,
    ShadowsocksOutbound,
    ShadowTlsInbound,
    ShadowTlsOutbound,
    SingBoxConfig,
    SocksInbound,
    SocksOutbound,
    SshOutbound,
    TlsConfig,
    TorOutbound,
    TransportConfig,
    TrojanInbound,
    TrojanOutbound,
    TuicInbound,
    TuicOutbound,
    UrlTestOutbound,
    User,
    V2RayApiConfig,
    VlessInbound,
    VlessOutbound,
    VmessInbound,
    VmessOutbound,
    WireGuardInbound,
    WireGuardOutbound,
)

# Утилиты
from .utils import (
    create_example_config,
    generate_singbox_schema,
    validate_singbox_config,
)

__all__ = [
    # Sing-box models
    "SingBoxConfig",
    "LogLevel",
    "Network",
    "DomainStrategy",
    "TlsConfig",
    "MultiplexConfig",
    "TransportConfig",
    "DnsConfig",
    "DnsServer",
    "DnsRule",
    "AuthenticationConfig",
    "User",
    "NtpConfig",
    "InboundBase",
    "MixedInbound",
    "SocksInbound",
    "HttpInbound",
    "ShadowsocksInbound",
    "VmessInbound",
    "VlessInbound",
    "TrojanInbound",
    "Hysteria2Inbound",
    "WireGuardInbound",
    "TuicInbound",
    "ShadowTlsInbound",
    "DirectInbound",
    "Inbound",
    "OutboundBase",
    "ShadowsocksOutbound",
    "VmessOutbound",
    "VlessOutbound",
    "TrojanOutbound",
    "Hysteria2Outbound",
    "WireGuardOutbound",
    "HttpOutbound",
    "SocksOutbound",
    "TuicOutbound",
    "ShadowTlsOutbound",
    "DnsOutbound",
    "DirectOutbound",
    "BlockOutbound",
    "SelectorOutbound",
    "UrlTestOutbound",
    "HysteriaOutbound",
    "AnyTlsOutbound",
    "SshOutbound",
    "TorOutbound",
    "Outbound",
    "RouteConfig",
    "RouteRule",
    "ExperimentalConfig",
    "ClashApiConfig",
    "V2RayApiConfig",
    "CacheFileConfig",
    "ObservatoryConfig",
    # Utilities
    "create_example_config",
    "validate_singbox_config",
    "generate_singbox_schema",
]
